In [12]:
#PCA

import pandas as pd
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from matplotlib.patches import FancyArrowPatch
from mpl_toolkits.mplot3d import proj3d
import matplotlib.pyplot as plt
%matplotlib inline  
from numpy import linalg as LA

# obtained from http://stackoverflow.com/questions/22867620/putting-arrowheads-on-vectors-in-matplotlibs-3d-plot
class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)


DIM_INI = 3
N_DATA  = 1000
NEW_DIM = 2

np.random.normal()

cov_mat = np.random.rand(DIM_INI,DIM_INI)
cov_mat = np.dot(cov_mat,cov_mat.T)

mean_x  = np.random.rand(DIM_INI)

#Generate data
X       = np.random.multivariate_normal(mean_x,cov_mat,N_DATA)

#Normalize data
for i in range(DIM_INI):
    mean_xi = np.mean(X[:,i])
    std_xi  = np.std(X[:,i])
    X[:,i]=(X[:,i]-mean_xi)/std_xi
    mean_x[i] = (mean_x[i]-mean_xi)/std_xi

X_t     = X.T
cov_x   = np.cov(X_t)

eigenvals_x,eigenvects_x = LA.eig(cov_x)
eigenvects_x


array([[ 0.59937309,  0.80006514,  0.02544939],
       [ 0.564524  , -0.39994844, -0.7220484 ],
       [ 0.56750731, -0.44714317,  0.69137431]])

In [13]:
eigenvals_x[0] * eigenvects_x[:,0]

array([ 1.66355188,  1.56682872,  1.57510886])

In [14]:
np.dot(cov_x, eigenvects_x[:,0])

array([ 1.66355188,  1.56682872,  1.57510886])

In [4]:
eigenval_sort_idxs       = np.argsort(eigenvals_x)

#Obtain projection matrix
A       = np.empty((NEW_DIM,DIM_INI))
for i in range(NEW_DIM):
    A[i,:] = eigenvects_x[eigenval_sort_idxs[NEW_DIM-i],:]

#Obtain projected data
Proy    = np.dot(A, X_t)
A

array([[-0.57677162, -0.72847017, -0.36968326],
       [-0.57695735,  0.68363073, -0.44695552]])

In [ ]:
if DIM_INI == 3:
    fig = plt.figure(figsize=(16, 10))
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter(X[:,0], X[:,1], X[:,2], c='r', marker='o',alpha=.5)
    for v in eigenvects_x:
        a = Arrow3D([mean_x[0], v[0]], [mean_x[1], v[1]], [mean_x[2], v[2]], mutation_scale=20, lw=3,arrowstyle="-|>", color="b")
        ax.add_artist(a)
    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')
    plt.title('All data with original eigenvectors')
    plt.draw()
    plt.show()

In [3]:
#plot 2d data
if NEW_DIM == 2:
    Proy_t=Proy.T
    fig = plt.figure(figsize=(16, 10))
    ax = fig.add_subplot(111)
    for i in range(NEW_DIM):
        eig_vect = eigenvects_x[eigenval_sort_idxs[NEW_DIM-i],:]
        ax.arrow(mean_x[0],mean_x[1],eig_vect[0],eig_vect[1], head_width=0.05, head_length=0.1, fc='k', ec='k')
    ax.scatter(Proy_t[:,0], Proy_t[:,1], color = 'r', marker='o',alpha=.5)
    plt.title('Principal components')
    plt.draw()
    plt.show()
