In [7]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import normalize, scale, MinMaxScaler, StandardScaler
from sklearn.decomposition import PCA

In [2]:
class PCA_lucas: 
    def __init__(self, n_components = None):
        self.n_components = n_components
        self.W = None

    def standarize(self, data):
        return np.nan_to_num((data - self.mean)/self.std)

    def fit(self, X):
        self.mean = np.mean(X, axis=0)
        self.std = np.std(X, axis=0)
        standarized_X = self.standarize(X)
        #Get projection matrix
        print(standarized_X)
        cov_x   = np.cov(standarized_X.T)
        print(cov_x)
        eigenvalues, eigenvectors = np.linalg.eig(cov_x)
        eigenvalues_order = np.argsort(eigenvalues)[::-1]
        sorted_eigenvalues = eigenvalues[eigenvalues_order]
        print sorted_eigenvalues.shape
        sorted_eigenvectors = eigenvectors[:,eigenvalues_order]
        self.W = sorted_eigenvectors
        if self.n_components is not None:
            self.W = self.W[:,:self.n_components]
        return standarized_X
        
    
    def transform(self, X):
        standarized_X = self.standarize(X)
        return np.dot(standarized_X, self.W)
    
    def fit_transform(self, X):
        return self.transform(standarized_X)

random data generation

In [12]:
n = 10
a = np.arange(n)
b = []
for i in range(n):
    unit = 1
    if i % 2 == 0:
        unit *= -1
    b.append(unit)
    
b = np.array(b).astype(np.float32)/5.0        
X = np.column_stack((a,a+b))

print(X)
pca_lucas = PCA_lucas(2)
X_pca_lucas = pca_lucas.fit_transform(X[:,:])
print(X_pca_lucas)

[[ 0.  -0.2]
 [ 1.   1.2]
 [ 2.   1.8]
 [ 3.   3.2]
 [ 4.   3.8]
 [ 5.   5.2]
 [ 6.   5.8]
 [ 7.   7.2]
 [ 8.   7.8]
 [ 9.   9.2]]
[[-1.56669891 -1.6130358 ]
 [-1.21854365 -1.13255703]
 [-0.87038827 -0.92663765]
 [-0.52223295 -0.44615883]
 [-0.17407766 -0.2402394 ]
 [ 0.17407766  0.24023932]
 [ 0.52223295  0.44615892]
 [ 0.87038827  0.92663753]
 [ 1.21854365  1.13255715]
 [ 1.56669891  1.6130358 ]]
[[ 1.11111114  1.10857007]
 [ 1.10857007  1.1111111 ]]
(2,)
[[ -0.14142136  -0.14142136]
 [  1.55563492   0.14142137]
 [  2.68700577  -0.14142134]
 [  4.38406204   0.14142139]
 [  5.51543289  -0.14142132]
 [  7.21248917   0.14142141]
 [  8.34386002  -0.1414213 ]
 [ 10.04091629   0.14142143]
 [ 11.17228714  -0.14142127]
 [ 12.86934342   0.14142146]]


In [13]:
print(X)
plt.plot(X[:,0], X[:,1], '.')
plt.show()

[[ 0.  -0.2]
 [ 1.   1.2]
 [ 2.   1.8]
 [ 3.   3.2]
 [ 4.   3.8]
 [ 5.   5.2]
 [ 6.   5.8]
 [ 7.   7.2]
 [ 8.   7.8]
 [ 9.   9.2]]


In [24]:
plt.plot(X_pca_lucas[:,0], X_pca_lucas[:,1], '.')
plt.show()

In [15]:
pca = PCA()
X_normalized = MinMaxScaler().fit_transform(X)
X_standarized = StandardScaler().fit_transform(X.astype(np.float32))
X_unnormalized_pca =  pca.fit_transform(X)
X_normalized_pca =  pca.fit_transform(X_normalized)
X_standarized_pca = pca.fit_transform(X_standarized)

In [21]:
plt.plot(X_normalized_pca[:,0], X_normalized_pca[:,1], '.')
plt.show()

In [22]:
plt.plot(X_unnormalized_pca[:,0], X_unnormalized_pca[:,1], '.')
plt.show()

In [23]:
plt.plot(X_standarized_pca[:,0], X_standarized_pca[:,1], '.')
plt.show()