In [40]:
import numpy as np

In [41]:
#X1= np.column_stack(([9, 4, 5, 7, 8, 2], [6, 7, 4, 2, 1, 3]))
n_attributes = 2
n_data = 10
X2 = 10 * np.random.uniform(0,1,n_data*n_attributes).reshape((n_data,n_attributes))
X = np.vstack((X1,X2))
X

array([[  9.78201483,  11.29181946],
       [  9.48031382,  11.00349368],
       [  8.14745305,   9.72368839],
       [ 10.98843458,   9.30236495],
       [  9.56353234,   8.64887604],
       [  8.71550983,   8.43486564],
       [  8.68069675,  10.77834639],
       [ 10.61293232,   9.4225873 ],
       [ 12.70266655,   8.48021842],
       [  9.54807706,   9.78669531],
       [  9.73788597,  10.52205618],
       [ 12.37374885,  13.13152788],
       [  9.8414863 ,   7.96110083],
       [ 10.09412827,  13.55636359],
       [ 10.36463085,  10.7913078 ],
       [ 11.51056148,   9.6428957 ],
       [  8.38522414,  13.53662131],
       [  2.63916255,   3.62416439],
       [  2.53281341,   3.07359884],
       [  2.82234549,   2.90083095],
       [  6.48517887,   0.9703061 ],
       [  4.06236461,   1.70164549],
       [  5.30944818,   5.03521151],
       [  0.64746963,   7.38005076],
       [  2.37659895,   4.16946355],
       [  3.31592683,   4.32245227],
       [  5.36772867,   3.17722984]])

In [51]:
from sklearn.cluster import Birch
import numpy as np
threshold_ = 3
mean1 = [10, 10]
mean2 = [20, 20]
mean3 = [10, 30]
mean4 = [50, 50]
cov1 = [[2.5, 0], [0, 2.5]]
cov2 = [[1, 0], [0, 1]]
X1= np.random.multivariate_normal(mean1, cov1, 17)
X2= np.random.multivariate_normal(mean2, cov1, 17)
X3= np.random.multivariate_normal(mean3, cov1, 17)
X4 = np.random.multivariate_normal(mean4, cov2,15)
X = np.vstack((X1,X2,X3,X4))
order = np.arange(len(X))
np.random.shuffle(order)
X = X[order]
brc = Birch(branching_factor=50, n_clusters=None, threshold=threshold_,
compute_labels=True)
brc.fit(X)


brc.predict(X)

array([0, 1, 1, 2, 1, 3, 3, 3, 1, 2, 0, 3, 0, 0, 3, 0, 2, 1, 3, 2, 3, 1, 3,
       1, 0, 0, 2, 3, 0, 0, 2, 1, 1, 0, 3, 2, 3, 2, 2, 1, 3, 0, 2, 2, 2, 1,
       1, 3, 0, 2, 1, 0, 3, 3, 1, 0, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1])

In [52]:
brc.subcluster_centers_

array([[ 10.38120866,  30.09795644],
       [  9.90079753,   9.76909056],
       [ 19.7689992 ,  19.53467244],
       [ 50.10922134,  50.22058974]])

In [53]:
import matplotlib.pyplot as plt
labels = brc.labels_
unique_labels = set(labels)
colors = plt.cm.Spectral(np.linspace(0, 1, len(unique_labels)))
centers = brc.subcluster_centers_
print centers

[[ 10.38120866  30.09795644]
 [  9.90079753   9.76909056]
 [ 19.7689992   19.53467244]
 [ 50.10922134  50.22058974]]


In [54]:
plt.plot(centers[:, 0], centers[:, 1], 'x')
for center, label in zip(centers, range(max(labels) + 1)) :
    print center
    class_member_mask = (labels == label)
    X_class = X[class_member_mask]
    radius = 0
    for member in X_class:
        distance = np.linalg.norm(member - center)
        if distance > radius:
            radius = distance
    print radius
    circle = plt.Circle(center,radius,color='r',fill=False)
    plt.gca().add_artist(circle)
for label, col in zip(unique_labels, colors):
    class_member_mask = (labels == label)
    X_class = X[class_member_mask]
    plt.plot(X_class[:, 0], X_class[:, 1], 'o', markerfacecolor=col)
plt.margins(0.2,0.2)
plt.show()

[ 10.38120866  30.09795644]
3.00486281612
[ 9.90079753  9.76909056]
4.3288381855
[ 19.7689992   19.53467244]
3.75778985779
[ 50.10922134  50.22058974]
1.9074036073


In [55]:
X

array([[ 10.70150872,  32.32609682],
       [ 10.32134918,  12.20560906],
       [ 10.65483218,  11.51255129],
       [ 21.25394025,  19.30545636],
       [  9.42273932,   7.31569221],
       [ 48.47257221,  50.01989354],
       [ 50.79839463,  51.1855896 ],
       [ 49.75620328,  50.53395255],
       [  9.87185228,   8.57154519],
       [ 20.50600693,  21.62218895],
       [ 11.33728416,  30.97739675],
       [ 50.97167213,  48.51930577],
       [  9.23202995,  30.34488094],
       [ 11.89710796,  31.30289894],
       [ 49.29029394,  50.24631046],
       [  9.63899692,  27.41173292],
       [ 18.37820858,  18.89321346],
       [ 11.45507201,   9.51690608],
       [ 50.14329425,  50.78391557],
       [ 18.11021204,  19.72270494],
       [ 50.0772085 ,  50.0935676 ],
       [  9.39278211,  10.24615452],
       [ 50.16116409,  49.89755382],
       [  6.09524443,   7.70593627],
       [ 11.32912962,  29.51444294],
       [  9.52178842,  30.78338568],
       [ 18.78263221,  17.94163448],
 